version: "3.9"

services:
  redis: 
    image: redis:latest 
    restart: always 
    ports: 
      - "6379:6379"
  
  worker: 
    build: .
    restart: always 
    environment: 
      CELERY_BROKER_URL: redis://redis:6379 
      CELERY_RESULT_BACKEND: redis://redis:6379 
    command: poetry run celery --app spamoverflow.tasks.spamscan worker --loglevel=info