@baseUrl = http://localhost:6400

### List all submitted emails for a given customer.
GET {{baseUrl}}/api/v1/customers/testing/emails

### Get information for a particular email.
GET {{baseUrl}}/api/v1/customers/testing/emails/9d0ee3d9-68e8-4606-8e09-25b37e9d9a50

### Post a new email scan request.
POST {{baseUrl}}/api/v1/customers/testing/emails
Content-Type: application/json

{
  "metadata": {
    "spamhammer": "0|12"
  },
  "contents": {
    "to": "test1@gmail.com",
    "from": "test2@gmail.com",
    "subject": "This is a useless email"
  }
}

### Get malicious senders of emails.
GET {{baseUrl}}/api/v1/customers/{customer_id}/reports/actors

### Get users who have received malicious emails.
GET{{baseUrl}}/api/v1/customers/{customer_id}/reports/recipients

### Health
GET {{baseUrl}}/api/v1/health